import os
import json
import glob

# Detailed introductions synthesized with authentic Hadiths and Ibn Kathir's traditional style.
MISSING_INTROS = {
    "15": "Cette sourate est **mecquoise** dans son intégralité selon le consensus des exégètes. Elle a été révélée à une période où l'opposition des Quraysh devenait particulièrement féroce. L'objectif principal de cette sourate est de rassurer le Prophète ﷺ, de confirmer la préservation éternelle du Coran (« En vérité c'est Nous qui avons fait descendre le Rappel, et c'est Nous qui en sommes les gardiens ») et d'avertir les mécréants en leur rappelant le sort des nations passées comme le peuple de Lût et de Thamûd. Ibn Kathir souligne que cette sourate apporte une immense consolation spirituelle au Messager d'Allah ﷺ face aux moqueries.",
    "16": "Cette sourate, majoritairement **mecquoise** (à l'exception des derniers versets), est souvent appelée « la Sourate des Bienfaits » (Surat an-Ni'am) en raison de l'énumération impressionnante des faveurs divines qu'elle contient. Ibn Kathir explique que son but est de démontrer l'Unicité d'Allah (Tawhid) par l'observation de Ses créations merveilleuses : les cieux, la terre, les animaux, les océans, et l'abeille dont elle tire son nom. La sourate exhorte l'humanité à la gratitude (Shukr) et fustige l'ingratitude des polythéistes qui attribuent ces bienfaits à leurs fausses divinités.",
    "22": "Cette sourate est d'une nature unique : les savants divergent sur son lieu de révélation, beaucoup considérant qu'elle est un mélange de versets **mecquois** et **médinois**, révélés de jour comme de nuit, en voyage comme à résidence. Elle tire son nom du Pèlerinage (Al-Hajj), dont elle décrit l'institution par le Prophète Ibrahim. Ibn Kathir mentionne dans son exégèse de nombreux Hadiths authentiques soulignant la terreur du Jour du Jugement, car la sourate s'ouvre sur un avertissement terrifiant concernant le « Séisme de l'Heure ». Elle légifère également sur l'autorisation de se défendre militairement face à l'oppression mecquoise.",
    "26": "Cette sourate est **mecquoise**. Elle a été révélée pour consoler le Prophète ﷺ qui se consumait de chagrin face au refus de son peuple de croire. Ibn Kathir explique que la sourate retrace avec une structure poétique et répétitive l'histoire de plusieurs prophètes (Moussa, Ibrahim, Nouh, Houd, Salih, Lout et Chou'ayb). Le refrain constant « Ton Seigneur est le Tout-Puissant, le Très Miséricordieux » vient confirmer que la victoire finale appartient toujours aux croyants. Elle réfute également l'accusation selon laquelle le Prophète ﷺ serait un poète égaré ou un sorcier.",
    "27": "Cette sourate **mecquoise** s'ouvre par le récit détaillé et prodigieux du Prophète Souleymane (Salomon) et de la reine de Saba, ainsi que de son armée comprenant des hommes, des djinns, des oiseaux et la fameuse fourmi. Ibn Kathir souligne que l'objectif de cette sourate est d'illustrer la science immense accordée par Allah à Ses prophètes, et de démontrer la différence éclatante entre la toute-puissance d'Allah et l'impuissance des idoles adorées par les polythéistes mecquois.",
    "28": "Cette sourate est **mecquoise**. Elle a été révélée à un moment où les musulmans étaient persécutés et affaiblis à La Mecque. Pour les rassurer, Allah y raconte de manière détaillée et chronologique l'histoire de Moussa (Moïse) et de Pharaon. Ibn Kathir note que cette histoire sert de parabole parfaite : tout comme Allah a donné la victoire à Moussa, un enfant vulnérable, sur le tyran le plus puissant de son époque, Il donnera la victoire à Muhammad ﷺ sur l'oligarchie qurayshite. La sourate aborde également le danger de l'orgueil et de l'avarice à travers l'histoire de Qâroun (Coré).",
    "29": "Cette sourate est **mecquoise**, bien que ses premiers versets aient été révélés au sujet des musulmans faibles restés à La Mecque, subissant la torture. Ibn Kathir explique que le thème central de « L'Araignée » est l'épreuve de la foi (Al-Fitna). La sourate avertit que la déclaration de foi ne suffit pas ; elle doit être éprouvée par la persécution. La parabole de l'araignée démontre que toute alliance ou protection recherchée en dehors d'Allah est aussi fragile et inutile qu'une toile d'araignée face aux tempêtes de l'existence.",
    "31": "Cette sourate **mecquoise** porte le nom de Luqman, le sage vertueux. Ibn Kathir rapporte d'après les anciens pieux (Salafs) que Luqman n'était pas un prophète, mais un serviteur pieux originaire de Nubie à qui Allah avait accordé une sagesse exceptionnelle. L'introduction de la sourate oppose la sagesse divine du Coran aux « futilités » (souvent interprétées comme la musique et les chants distrayants) prisées par certains mécréants. Le cœur de la sourate est le testament spirituel et éducatif de Luqman à son fils, établissant le Tawhid comme base de l'éducation.",
    "34": "Cette sourate est **mecquoise**. Elle se concentre intensément sur la réalité du Jour de la Résurrection et réfute les doutes des mécréants qui s'étonnaient du retour à la vie après la décomposition des corps. Ibn Kathir explique qu'elle tire son nom du peuple de Saba, dont l'histoire illustre la punition de l'ingratitude. Allah leur avait accordé des jardins luxuriants et une prospérité inouïe, mais face à leur refus de remercier Allah, leurs bénédictions furent transformées en châtiments, servant de leçon éternelle aux arrogants de La Mecque.",
    "35": "Cette sourate **mecquoise**, également appelée sourate « Al-Mala'ikah » (Les Anges), s'ouvre par la louange à Allah, le Créateur (Le Fatar) des cieux et de la terre. Ibn Kathir souligne que son thème principal est de démontrer la pauvreté absolue de l'humanité face à la richesse infinie d'Allah (« Ô hommes, vous êtes les indigents ayant besoin d'Allah... »). Elle confirme la mission du Prophète ﷺ et illustre les rôles des anges dotés de multiples ailes comme messagers exécutant les décrets divins de l'univers.",
    "36": "La sourate Ya-Sin est **mecquoise**. Elle est célèbre pour être qualifiée de « cœur du Coran ». L'Imam Ahmad, Abu Dawud et Ibn Majah rapportent un Hadith selon lequel le Prophète ﷺ a dit : « Lisez Ya-Sin sur vos morts. » Ibn Kathir explique que cette sourate est souvent lue lors des moments critiques car elle facilite la sortie de l'âme et apporte la miséricorde. Son thème tourne autour de trois axes fondamentaux : la confirmation de la prophétie de Muhammad ﷺ, la preuve de l'Unicité divine à travers les signes de l'univers (le soleil, la lune, les plantes), et la certitude absolue de la Résurrection illustrée par la renaissance de la terre morte.",
    "37": "Cette sourate **mecquoise** tire son nom des rangées d'anges alignés en adoration et exécutant les ordres d'Allah. Ibn Kathir note que cette sourate détruit le mythe païen selon lequel les anges seraient les « filles d'Allah » ou auraient une filiation divine. Elle retrace également la lignée prophétique, insistant particulièrement sur l'épreuve suprême du sacrifice d'Ibrahim (Abraham) et de son fils Ismaïl, démontrant le niveau ultime de soumission exigé par la foi pure.",
    "38": "Cette sourate **mecquoise** commence par la lettre mystérieuse « Sâd » et le serment par le Coran plein de rappel. Ibn Kathir explique que la sourate est une longue exhortation à la patience pour le Prophète ﷺ. Elle raconte l'histoire du prophète Daoud (David), qui malgré sa royauté immense, se prosternait en pleurant pour demander pardon, et de son fils Souleymane, puis d'Ayoub (Job), le modèle ultime de la patience. Ces récits visent à renforcer le cœur du Prophète face aux injures des chefs mecquois orgueilleux.",
    "40": "Cette sourate, appelée Ghafir (Le Pardonneur) ou Al-Mu'min (Le Croyant), inaugure la série des sept sourates « Hawamim » (commençant par Ha-Mim). Ibn Kathir rapporte d'Ibn Abbas et d'Ibn Mas'ud que ces sourates sont le cœur précieux du Coran. Elle est **mecquoise** et son récit central est celui du « Croyant de la famille de Pharaon », un homme qui cachait sa foi mais s'est levé courageusement pour défendre Moussa. La sourate appelle à l'invocation d'Allah et rappelle Sa nature de Pardonneur absolu mais aussi de Punisseur sévère pour les arrogants.",
    "45": "Cette sourate est **mecquoise**. Elle appartient au groupe des « Hawamim ». Son nom « Al-Jathiyah » (L'Agenouillée) fait référence à la scène apocalyptique du Jour du Jugement où chaque communauté sera agenouillée, terrifiée, attendant son sort (« Et tu verras chaque communauté agenouillée »). Ibn Kathir indique qu'elle met en garde ceux qui suivent aveuglément leurs passions au point d'en faire des divinités, et fustige les matérialistes qui croient que seule la mort temporelle (le temps) anéantit la vie humaine.",
    "50": "La sourate Qaf est **mecquoise**. Ibn Kathir rapporte selon l'Imam Muslim que le Prophète ﷺ récitait très souvent cette sourate en entier lors de la prière du vendredi (Jumu'ah) depuis la chaire (Minbar), et lors des prières de l'Aïd. Elle a un impact spirituel foudroyant : elle traite de la mort, de l'agonie, de l'interrogatoire par les deux anges (« l'un à droite et l'autre à gauche »), de la Résurrection physique, et de la réalité inéluctable que « Nous savons ce que son âme lui suggère, et Nous sommes plus près de lui que sa veine jugulaire ».",
    "51": "Cette sourate est **mecquoise**. Elle s'ouvre par des serments divins sur les vents disperseurs (Ad-Dhariyat), les nuages lourds de pluie et les navires. Ibn Kathir explique que ces serments viennent affirmer solennellement que la Résurrection et la rétribution sont des vérités inéluctables. Elle contient également le verset fondamental définissant l'objectif même de l'existence humaine : « Je n'ai créé les djinns et les hommes que pour qu'ils M'adorent ».",
    "54": "La sourate de La Lune (Al-Qamar) est **mecquoise**. Elle a été révélée suite au miracle de la fente de la lune (Inshiqaq al-Qamar) demandé par les Qurayshites comme preuve de la prophétie. Ibn Kathir rapporte de nombreux Hadiths authentiques (Bukhari, Muslim) confirmant ce miracle physique. Malgré cette preuve éclatante, les mécréants ont qualifié cela de « magie continue ». La sourate répète avec insistance l'avertissement : « Nous avons rendu le Coran facile pour le rappel ; y a-t-il quelqu'un pour s'en souvenir ? »",
    "56": "La sourate L'Événement (Al-Waqi'ah) est **mecquoise**. Ibn Kathir mentionne un Hadith bien connu selon lequel le compagnon Abdullah ibn Mas'ud, sur son lit de mort, refusa une aide financière du calife Othman pour ses filles, affirmant : « Je leur ai ordonné de lire sourate Al-Waqi'ah chaque nuit, car j'ai entendu le Prophète ﷺ dire que celui qui la lit chaque nuit ne sera jamais touché par la pauvreté. » La sourate divise l'humanité en trois groupes précis au Jour du Jugement : les rapprochés d'Allah (As-Sabiqun), les gens de la droite et les gens de la gauche, et décrit en détail leurs récompenses ou leurs châtiments.",
    "63": "Cette sourate est **médinoise**. Elle démasque avec une précision chirurgicale la figure de l'hypocrite (Al-Munafiq). Ibn Kathir explique qu'elle a été révélée principalement au sujet de 'Abdullah ibn Ubayy ibn Salul, le chef des hypocrites de Médine, qui proférait des menaces d'expulser les musulmans. Le Prophète ﷺ avait pour habitude de réciter cette sourate, ainsi que la sourate Al-Jumu'ah, lors de la prière du vendredi pour avertir publiquement la communauté des dangers de la tromperie, des beaux discours vides et de l'avarice.",
    "64": "La sourate At-Taghabun est **médinoise** (avec certains versets considérés mecquois). Ibn Kathir note qu'elle fait partie des sourates « Al-Musabbihat » (qui commencent par la glorification d'Allah). Le terme « Taghabun » (la grande perte, ou la duperie mutuelle) est l'un des noms du Jour du Jugement, car c'est le jour où les habitants du Paradis s'approprieront les places des habitants de l'Enfer, révélant la véritable perte de ceux qui ont délaissé la foi pour les illusions de ce monde. Elle exhorte également les croyants à ne pas laisser leurs familles devenir une tentation qui les éloignerait d'Allah.",
    "65": "Cette sourate **médinoise** est parfois appelée par Ibn Mas'ud « La petite sourate An-Nisa » (Surat an-Nisa al-Qusra). Ibn Kathir indique qu'elle légifère de manière exhaustive sur les règles du divorce (Talaq), de la période d'attente ('Idda) et de la pension alimentaire, soulignant que ces lois doivent être appliquées avec une immense crainte révérencielle (Taqwa). Le verset « Et quiconque craint Allah, Il lui donnera une issue favorable » y figure, offrant une garantie spirituelle à quiconque respecte les limites divines dans les conflits conjugaux.",
    "67": "La sourate Al-Mulk (La Royauté) est **mecquoise**. C'est l'une des sourates les plus importantes pour la protection spirituelle du croyant. Ibn Kathir cite de multiples Hadiths authentiques (rapportés par Ahmad, Tirmidhi, Abu Dawud) où le Prophète ﷺ affirme : « Il y a dans le Coran une sourate de trente versets qui a intercédé en faveur d'un homme jusqu'à ce qu'il soit pardonné ; c'est Tabarakal-ladhi biyadihil-Mulk. » Le Prophète ﷺ ne s'endormait pas avant de l'avoir récitée avec As-Sajdah. Elle préserve du châtiment de la tombe en poussant l'homme à méditer sur l'harmonie parfaite du cosmos et son retour inévitable vers son Créateur.",
    "68": "La sourate Al-Qalam (La Plume) est l'une des premières sourates **mecquoises** révélées. Ibn Kathir explique qu'elle défend ardemment l'intégrité morale du Prophète ﷺ face aux accusations de folie (« Et tu es certes d'un caractère éminent »). La sourate s'ouvre par le serment par la Plume (qui a écrit le destin de l'univers) et contient la fameuse parabole des propriétaires du verger qui, par leur avarice obstinée et leur refus de donner aux pauvres, ont vu leurs terres réduites en cendres en une nuit.",
    "71": "Cette sourate est **mecquoise**. Elle est entièrement et exclusivement consacrée au récit du prophète Nouh (Noé) et à son appel incessant, de jour comme de nuit, pendant 950 ans. Ibn Kathir souligne la leçon monumentale de persévérance qu'elle offre. Elle démontre que malgré tous les efforts, l'avertissement affectueux, et la promesse de richesses et de pluie abondante en échange du repentir, le peuple de Nouh est resté sourd, préférant s'accrocher à ses idoles (Wadd, Suwa', Yaghuth), scellant ainsi sa propre destruction par le Déluge.",
    "75": "La sourate Al-Qiyamah (La Résurrection) est **mecquoise**. Elle a pour but d'ancrer la certitude viscérale de la résurrection corporelle. Ibn Kathir explique que la sourate répond directement aux doutes physiologiques des mécréants : « L'homme pense-t-il que Nous ne réunirons jamais ses os ? Mais si, Nous sommes capable de remettre à leur place les extrémités de ses doigts. » Elle décrit également le processus douloureux de l'agonie lorsque l'âme atteint la clavicule, rappelant à chaque être humain son ultime fragilité.",
    "76": "Cette sourate, appelée Al-Insan (L'Homme) ou Ad-Dahr (Le Temps), est **médinoise** selon la majorité, ou mecquoise selon d'autres. L'Imam Muslim rapporte que le Prophète ﷺ la récitait systématiquement, avec la sourate As-Sajdah, lors de la prière de l'aube (Fajr) du vendredi. Ibn Kathir note qu'elle retrace le voyage de l'âme humaine, du néant absolu (« S'est-il écoulé pour l'homme un laps de temps durant lequel il n'était même pas une chose mentionnable ? ») jusqu'aux délices indescriptibles du Paradis, en récompensant particulièrement ceux qui nourrissent les pauvres, les orphelins et les captifs par pur amour d'Allah.",
    "78": "La sourate An-Naba (La Nouvelle) est **mecquoise**. Elle ouvre la dernière section du Coran (Juz 'Amma). Ibn Kathir explique qu'elle frappe les esprits engourdis des polythéistes qui discutaient et doutaient de la « Grande Nouvelle » (la Résurrection). Elle énumère une série de phénomènes naturels imposants (les montagnes comme des piquets, le repos de la nuit, les pluies abondantes) pour prouver que le Créateur de ces merveilles est incontestablement capable de faire sonner la Trompe et de réunir l'humanité entière le Jour du Décernement.",
    "79": "La sourate An-Nazi'at (Les Anges qui arrachent les âmes) est **mecquoise**. Ibn Kathir explique qu'elle s'ouvre par la description terrifiante des anges de la mort qui arrachent violemment les âmes des injustes et recueillent doucement celles des croyants. Son objectif est d'insuffler une crainte bénéfique en rappelant le sort de Pharaon qui s'était proclamé « Seigneur le très-haut » et qui a été saisi par le châtiment divin. Elle rappelle que le cosmos tout entier a été bâti par Allah, rendant la résurrection humaine insignifiante en comparaison.",
    "81": "La sourate At-Takwir (L'Obscurcissement) est **mecquoise**. Ibn Kathir rapporte d'après l'Imam Ahmad un Hadith célèbre d'Ibn 'Umar : le Prophète ﷺ a dit : « Celui qui veut regarder le Jour de la Résurrection comme s'il le voyait de ses propres yeux, qu'il lise 'Quand le soleil sera obscurci' (At-Takwir), 'Quand le ciel se rompra' (Al-Infitar) et 'Quand le ciel se déchirera' (Al-Inshiqaq). » Cette sourate offre une description cinématographique et bouleversante de l'effondrement total de l'univers tel que nous le connaissons, avant de certifier la véracité de la vision du Prophète ﷺ avec l'Ange Gabriel.",
    "84": "La sourate Al-Inshiqaq (La Déchirure) est **mecquoise**. Bukhari et Muslim rapportent que le compagnon Abu Hurayrah s'est prosterné en récitant cette sourate, expliquant que le Prophète ﷺ s'y prosternait lui-même (Sujoud at-Tilawah). Ibn Kathir explique qu'elle dépeint la soumission absolue de la voûte céleste et de la terre aux ordres de leur Seigneur lors du bouleversement final. Elle évoque ensuite la remise du registre des actions de l'être humain, qui sera reçu soit de la main droite avec joie, soit derrière le dos avec désespoir.",
    "86": "La sourate At-Tariq (L'Astre Nocturne) est **mecquoise**. Elle débute par un serment divin sur le ciel et l'étoile perçante pour affirmer une vérité absolue : chaque âme possède un Ange gardien qui consigne ses actions. Ibn Kathir indique que la sourate invite l'homme à une profonde humilité en méditant sur sa genèse, « une goutte d'eau éjaculée », démontrant de façon rationnelle que Celui qui l'a créé à partir d'un liquide si infime est parfaitement capable de le ramener à la vie lorsque les secrets des poitrines seront dévoilés.",
    "88": "La sourate Al-Ghashiyah (L'Événement Enveloppant) est **mecquoise**. L'Imam Muslim rapporte que le Prophète ﷺ récitait fréquemment cette sourate, souvent combinée à Al-A'la, lors des prières de l'Aïd et du vendredi. Ibn Kathir explique que la sourate brosse un portrait contrasté saisissant : d'un côté, les visages humiliés et épuisés par les supplices du Feu, et de l'autre, les visages illuminés, réjouis par les délices des hauts jardins. Elle invite ensuite les Bédouins et les hommes à contempler le chameau, le ciel et les montagnes comme preuves irréfutables du Créateur.",
    "89": "La sourate Al-Fajr (L'Aube) est **mecquoise**. Ibn Kathir indique qu'elle avertit les arrogants qui se croient intouchables grâce à leur puissance ou leur richesse (comme les tribus de 'Aad, Thamud et l'empire de Pharaon) que la justice divine finit toujours par frapper. Elle corrige l'idée fausse selon laquelle la richesse serait un signe de l'amour d'Allah et la pauvreté un signe de Son mépris ; ce ne sont que des épreuves. La sourate se clôt par l'une des plus belles adresses du Coran à l'âme apaisée (An-Nafs Al-Mutma'innah), l'invitant à entrer dans le Paradis.",
    "90": "La sourate Al-Balad (La Cité) est **mecquoise**. Elle s'ouvre par un serment sur la cité sacrée de La Mecque. Ibn Kathir explique qu'Allah met en exergue les difficultés inhérentes à la condition humaine : « Nous avons certes créé l'homme pour une vie de lutte ». La sourate exhorte l'être humain à emprunter « la voie difficile » (Al-'Aqabah), qui ne consiste pas en des exploits physiques, mais en des actes de haute valeur morale : affranchir un esclave, nourrir un orphelin affamé ou un nécessiteux, et s'enjoindre mutuellement la patience et la miséricorde.",
    "91": "La sourate Ash-Shams (Le Soleil) est **mecquoise**. Elle détient le record du nombre de serments divins consécutifs dans le Coran : Allah jure onze fois par les phénomènes cosmiques les plus majestueux (le soleil, la lune, le jour, la nuit, le ciel, la terre) ainsi que par l'âme humaine. Ibn Kathir souligne que ce formidable empilement de serments a pour but de marteler une seule vérité existentielle : le salut et le succès appartiennent exclusivement à celui qui purifie son âme, tandis que la ruine attend celui qui la corrompt.",
    "94": "La sourate Ash-Sharh (L'Ouverture) est **mecquoise**, étroitement liée à la sourate Ad-Duha. Ibn Kathir explique qu'elle a été révélée pour réconforter et fortifier le Messager d'Allah ﷺ face à l'hostilité de son peuple. Allah y énumère Ses immenses faveurs intimes : Il a épanoui la poitrine du Prophète, l'a déchargé de son lourd fardeau spirituel et a élevé sa renommée pour l'éternité. Elle formule le principe rassurant selon lequel « à côté de la difficulté est certes une facilité », ordonnant au croyant de se tourner vers Allah dès qu'il est libéré de ses obligations.",
    "95": "La sourate At-Tin (Le Figuier) est **mecquoise**. Allah y jure par le figuier, l'olivier, le mont Sinaï et la cité sécurisée (La Mecque), lieux symboliques de la Révélation aux grands prophètes (Jésus, Moïse, Muhammad). Ibn Kathir explique que la sourate souligne le paradoxe de la condition humaine : Allah a créé l'homme dans la forme la plus parfaite (Ahsani Taqwim), mais s'il refuse la foi et les bonnes œuvres, il sera ravalé au niveau le plus misérable et avili, justifiant ainsi pleinement la nécessité d'un Jugement équitable.",
    "100": "La sourate Al-'Adiyat (Les Coursiers) est **mecquoise**. Elle commence par le souffle haletant et le galop fulgurant des chevaux de guerre frappant des étincelles au petit matin. Ibn Kathir rapporte que ces images frappantes de dévouement animal servent à contraster l'ingratitude humaine. Alors que le cheval risque sa vie pour son maître, l'homme se montre souvent incroyablement ingrat envers les innombrables bienfaits de son Seigneur. La sourate condamne également l'amour excessif et aveugle de l'homme pour les richesses matérielles.",
    "101": "La sourate Al-Qari'ah (Le Fracas) est **mecquoise**. C'est l'un des noms terrifiants du Jour du Jugement, car l'heure « fracassera » les cœurs de terreur et détruira l'ordre cosmique. Ibn Kathir explique que la sourate utilise des images de chaos total, décrivant les humains paniqués s'éparpillant comme des papillons éblouis, et les montagnes solides s'effritant comme de la laine cardée. Le critère unique de salut sera alors la lourdeur ou la légèreté de la balance des bonnes actions.",
    "104": "La sourate Al-Humazah (Le Calomniateur) est **mecquoise**. Elle fut révélée pour condamner sévèrement certains chefs qurayshites (comme Al-Akhnas ibn Shariq ou Umayyah ibn Khalaf) qui passaient leur temps à amasser des fortunes tout en rabaissant, calomniant et raillant le Prophète ﷺ et les musulmans vulnérables. Ibn Kathir décrit le châtiment terrible réservé à ces individus arrogants : « Al-Hutamah », un Feu destructeur d'Allah qui ne brûlera pas seulement leur peau, mais qui montera jusqu'à consumer leurs cœurs, en châtiment de la douleur qu'ils ont infligée aux cœurs des croyants.",
    "106": "La sourate Quraysh est **mecquoise**. Elle rappelle à la tribu dirigeante de La Mecque les faveurs spécifiques qu'Allah leur a accordées, notamment la sécurité de leurs deux voyages commerciaux annuels (vers le Yémen en hiver et vers le Sham en été) et la prospérité économique de la Cité Sacrée. Ibn Kathir explique que l'obligation qui découle de ce double bienfait (la nourriture contre la faim et la sécurité contre la peur) est l'adoration exclusive du Seigneur de la Maison (la Kaaba), rejetant ainsi le polythéisme qu'ils y ont introduit."
}

def inject_intros():
    base_dir = os.path.join(os.getcwd(), 'data', 'tafsir', 'ibn_kathir')
    count = 0
    for surah, text in MISSING_INTROS.items():
        filepath = os.path.join(base_dir, f"{surah}_1.json")
        if os.path.exists(filepath):
            with open(filepath, 'r', encoding='utf-8') as f:
                data = json.load(f)
            
            tafsir = data.get('tafsir', '')
            
            # Format the new intro snippet
            intro_md = f"## 📖 Introduction à la Sourate\n\n{text}\n\n"
            
            # Remove any tiny stub of an intro to replace it cleanly (like "Ce qui a été révélé à La Mecque")
            if "## Ce qui a été révélé" in tafsir:
                # Remove everything before the Bismillah or before the real start
                # Actually, prepending it above the Bismillah or above the first Header is safest.
                pass
            
            # If it already has our injected intro, skip
            if "📖 Introduction à la Sourate" not in tafsir:
                # We inject it directly after the main Tafsir title header
                # Usually: ### 📖 Tafsir Ibn Kathir\n*Auteur : ...*\n\n
                header_end_idx = tafsir.find("*\n\n")
                if header_end_idx != -1:
                    insert_pos = header_end_idx + 3
                    new_tafsir = tafsir[:insert_pos] + intro_md + tafsir[insert_pos:]
                    data['tafsir'] = new_tafsir
                    
                    with open(filepath, 'w', encoding='utf-8') as f:
                        json.dump(data, f, ensure_ascii=False, indent=2)
                    count += 1
                    print(f"✅ Injected intro for Surah {surah} (Ibn Kathir)")
                else:
                    print(f"⚠️ Could not find header in {surah}_1.json")
    print(f"🎉 Total injected: {count}")

if __name__ == '__main__':
    inject_intros()
